// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VehicleParking.Infrastructure.Persistence.Databases;

#nullable disable

namespace VehicleParking.Infrastructure.Migrations
{
    [DbContext(typeof(ParkingDbContext))]
    partial class ParkingDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VehicleParking.Domain.Entities.ParkingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("Charge")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("SpaceNumber")
                        .HasColumnType("integer");

                    b.Property<DateTime>("TimeIn")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("TimeOut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VehicleReg")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VehicleType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SpaceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_parking_sessions_active_space")
                        .HasFilter("\"TimeOut\" IS NULL");

                    b.HasIndex("VehicleReg")
                        .IsUnique()
                        .HasDatabaseName("ix_parking_sessions_active_vehicle_reg")
                        .HasFilter("\"TimeOut\" IS NULL");

                    b.ToTable("parking_sessions", (string)null);
                });

            modelBuilder.Entity("VehicleParking.Domain.Entities.ParkingSpace", b =>
                {
                    b.Property<int>("Number")
                        .HasColumnType("integer");

                    b.HasKey("Number");

                    b.ToTable("parking_spaces", (string)null);

                    b.HasData(
                        new
                        {
                            Number = 1
                        },
                        new
                        {
                            Number = 2
                        },
                        new
                        {
                            Number = 3
                        },
                        new
                        {
                            Number = 4
                        },
                        new
                        {
                            Number = 5
                        },
                        new
                        {
                            Number = 6
                        },
                        new
                        {
                            Number = 7
                        },
                        new
                        {
                            Number = 8
                        },
                        new
                        {
                            Number = 9
                        },
                        new
                        {
                            Number = 10
                        },
                        new
                        {
                            Number = 11
                        },
                        new
                        {
                            Number = 12
                        },
                        new
                        {
                            Number = 13
                        },
                        new
                        {
                            Number = 14
                        },
                        new
                        {
                            Number = 15
                        },
                        new
                        {
                            Number = 16
                        },
                        new
                        {
                            Number = 17
                        },
                        new
                        {
                            Number = 18
                        },
                        new
                        {
                            Number = 19
                        },
                        new
                        {
                            Number = 20
                        },
                        new
                        {
                            Number = 21
                        },
                        new
                        {
                            Number = 22
                        },
                        new
                        {
                            Number = 23
                        },
                        new
                        {
                            Number = 24
                        },
                        new
                        {
                            Number = 25
                        },
                        new
                        {
                            Number = 26
                        },
                        new
                        {
                            Number = 27
                        },
                        new
                        {
                            Number = 28
                        },
                        new
                        {
                            Number = 29
                        },
                        new
                        {
                            Number = 30
                        },
                        new
                        {
                            Number = 31
                        },
                        new
                        {
                            Number = 32
                        },
                        new
                        {
                            Number = 33
                        },
                        new
                        {
                            Number = 34
                        },
                        new
                        {
                            Number = 35
                        },
                        new
                        {
                            Number = 36
                        },
                        new
                        {
                            Number = 37
                        },
                        new
                        {
                            Number = 38
                        },
                        new
                        {
                            Number = 39
                        },
                        new
                        {
                            Number = 40
                        },
                        new
                        {
                            Number = 41
                        },
                        new
                        {
                            Number = 42
                        },
                        new
                        {
                            Number = 43
                        },
                        new
                        {
                            Number = 44
                        },
                        new
                        {
                            Number = 45
                        },
                        new
                        {
                            Number = 46
                        },
                        new
                        {
                            Number = 47
                        },
                        new
                        {
                            Number = 48
                        },
                        new
                        {
                            Number = 49
                        },
                        new
                        {
                            Number = 50
                        });
                });

            modelBuilder.Entity("VehicleParking.Domain.Entities.ParkingSession", b =>
                {
                    b.HasOne("VehicleParking.Domain.Entities.ParkingSpace", null)
                        .WithMany()
                        .HasForeignKey("SpaceNumber")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
